# This is a basic workflow to help you get started with Actions

name: Deploy-On-Release

# Controls when the workflow will run
on:
  # Triggers the workflow on release
  release:
      types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  deploy:
    # The type of runner that the job will run on
    name: Gcloud Deploy
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-southeast1-docker.pkg.dev/ini-ai/plant-monitor/plant-monitor

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - id: 'auth'
        name: Authenticate to GCloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/693982092053/locations/global/workloadIdentityPools/ini-ai-pool/providers/gh-action-provider'
          service_account: 'ai-gar@ini-ai.iam.gserviceaccount.com'
      
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure Docker to Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        
      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Run a one-line script
        run: echo Do Do Done!
